version: "3.8"

services:
  el-java:
    build:
      context: .
      dockerfile: ./docker/java/Dockerfile
    image: el-java
    container_name: el-java
    command: tail -f /dev/null
    volumes:
      - ./src:/usr/src/src
